global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cost-web-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cost-web-app:8080']
        labels:
          application: 'cost-web-app'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

