apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: cost-web-app
  environment: production

images:
  - name: cost-web-app
    newName: your-docker-registry/cost-web-app
    newTag: latest

