apiVersion: v1
kind: Service
metadata:
  name: cost-web-app
  labels:
    app: cost-web-app
spec:
  type: NodePort
  selector:
    app: cost-web-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http

